<!DOCTYPE html>
<html lang="en">
<head>
    <title>ToDo</title>
    <link type="text/css" rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
</head>
<div class="container">
    <h1 class="row col-md-offset-1">
        Todo
    </h1>
    <div class="col-md-10 col-md-offset-1">
    <form action="" method="post">
        <div class="form-group">
            <label for="text1">Some Text Here</label>
            <input type="text" class="form-control" id="text1" placeholder="Text ..">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
    </form>
    </div>
</div>
</html>